# Generated by Django 3.0.6 on 2020-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
